services:
    tidecrud.form_serializer:
        class: Tide\TideCrudBundle\Helpers\FormErrorsSerializer
    tidecrud.crud_helper:
        class: Tide\TideCrudBundle\Helpers\CrudHelper
        arguments: ["@service_container"]
    tidecrud.twig_extension:
        class: Tide\TideCrudBundle\Twig\CrudExtension
        arguments: ["@tidecrud.crud_helper"]